# Generated by Django 5.1.4 on 2026-06-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quota_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
