# Generated by Django 5.1.4 on 2026-06-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='main', editable=False, max_length=8, unique=True)),
                ('site_name', models.CharField(default='MMFileTransfer', max_length=120)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('date_format', models.CharField(default='Y-m-d', max_length=32)),
                ('pagination_size', models.PositiveSmallIntegerField(default=25)),
                ('retention_enabled', models.BooleanField(default=False)),
                ('retention_days', models.PositiveSmallIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
                'db_table': 'config_site_settings',
            },
        ),
    ]
