# Generated by Django 5.1.4 on 2026-06-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ldap_attr_email',
            field=models.CharField(blank=True, default='mail', max_length=64),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ldap_attr_employee_id',
            field=models.CharField(blank=True, default='employeeNumber', max_length=64),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ldap_attr_first_name',
            field=models.CharField(blank=True, default='givenName', max_length=64),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ldap_attr_last_name',
            field=models.CharField(blank=True, default='sn', max_length=64),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ldap_base_dn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ldap_bind_dn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ldap_bind_password_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ldap_connect_timeout',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ldap_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ldap_server_uri',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ldap_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ldap_user_search_filter',
            field=models.CharField(blank=True, default='(uid=%(user)s)', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='session_idle_timeout_minutes',
            field=models.PositiveIntegerField(default=480),
        ),
    ]
