# Generated by Django 5.1.4 on 2026-06-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_sitesettings_ldap_attr_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_from_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='expiry_reminder_days',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notification_bcc',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='send_assignment_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='send_welcome_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_password_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
