# Generated by Django 5.1.4 on 2026-06-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_customfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_user_quota_gb',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
