# Generated by Django 5.1.4 on 2026-06-12 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_sharelink_sharelinkfile_sharelink_files_and_more'),
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='publicdownloadverification',
            name='public_down_stored__55b5c2_idx',
        ),
        migrations.RemoveField(
            model_name='publicdownloadverification',
            name='stored_file',
        ),
        migrations.AddField(
            model_name='publicdownloadverification',
            name='share_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='files.sharelink'),
        ),
        migrations.AddIndex(
            model_name='publicdownloadverification',
            index=models.Index(fields=['share_link', 'email'], name='public_down_share_l_af5830_idx'),
        ),
    ]
