# Generated by Django 5.1.4 on 2026-06-11 06:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CronLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=128)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('deleted_count', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_cron_log',
                'ordering': ('-finished_at',),
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('successful', models.BooleanField(default=False)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_login_attempt',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['identifier', 'created_at'], name='audit_login_identif_e78405_idx'), models.Index(fields=['ip_address', 'created_at'], name='audit_login_ip_addr_9fc7cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login failed'), ('user_created', 'User created (JIT/admin)'), ('upload', 'File uploaded'), ('download', 'File downloaded'), ('delete', 'File deleted'), ('settings_changed', 'Settings changed'), ('other', 'Other')], max_length=32)),
                ('message', models.CharField(blank=True, max_length=512)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_activity_log',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['actor', 'created_at'], name='audit_activ_actor_i_8a91d9_idx')],
            },
        ),
    ]
