# Generated by Django 5.1.4 on 2026-06-11 09:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_email', models.EmailField(blank=True, max_length=254)),
                ('via_public_link', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_events', to='files.storedfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_download_event',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['stored_file', 'created_at'], name='audit_downl_stored__f44556_idx')],
            },
        ),
    ]
