# Generated by Django 5.1.4 on 2026-06-12 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_downloadevent'),
        ('files', '0007_sharelink_sharelinkfile_sharelink_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadevent',
            name='share_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_events', to='files.sharelink'),
        ),
    ]
