# Generated by Django 5.1.4 on 2026-06-15 04:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_downloadevent_share_link'),
        ('files', '0008_migrate_public_links_to_sharelinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLinkView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_email', models.EmailField(blank=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='files.sharelink')),
            ],
            options={
                'db_table': 'audit_share_link_view',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['share_link', 'created_at'], name='audit_share_share_l_0574ef_idx')],
            },
        ),
    ]
