# Generated by Django 5.1.4 on 2026-06-11 07:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'files_category',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('temp_key', models.CharField(blank=True, max_length=512)),
                ('storage_key', models.CharField(blank=True, max_length=512)),
                ('thumbnail_key', models.CharField(blank=True, max_length=512)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('public_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('public_require_email_verify', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('download_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('pending_metadata', 'Pending metadata'), ('active', 'Active'), ('deleted', 'Deleted')], db_index=True, default='uploading', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='files', to='files.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files_stored_file',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FileAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_assignments', to=settings.AUTH_USER_MODEL)),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='files.storedfile')),
            ],
            options={
                'db_table': 'files_file_assignment',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_chunked', models.BooleanField(default=False)),
                ('multipart_upload_id', models.CharField(blank=True, max_length=255)),
                ('parts', models.JSONField(blank=True, default=list)),
                ('declared_size', models.BigIntegerField(default=0)),
                ('received_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
                ('stored_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_session', to='files.storedfile')),
            ],
            options={
                'db_table': 'files_upload_session',
            },
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['owner', 'status'], name='files_store_owner_i_5bea38_idx'),
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['status', 'created_at'], name='files_store_status_de00a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fileassignment',
            unique_together={('stored_file', 'recipient')},
        ),
    ]
