# Generated by Django 5.1.4 on 2026-06-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
