# Generated by Django 5.1.4 on 2026-06-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_storedfile_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
