# Generated by Django 5.1.4 on 2026-06-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_group'),
        ('files', '0003_storedfile_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='files', to='accounts.group'),
        ),
    ]
