# Generated by Django 5.1.4 on 2026-06-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_storedfile_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='public_allow_download',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='public_password_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
