# Generated by Django 5.1.4 on 2026-06-12 09:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_storedfile_public_allow_download_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StarredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='files.storedfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_stars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files_starred_file',
                'ordering': ('-created_at',),
                'unique_together': {('user', 'stored_file')},
            },
        ),
        migrations.AddField(
            model_name='storedfile',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_files', through='files.StarredFile', to=settings.AUTH_USER_MODEL),
        ),
    ]
