# Generated by Django 5.1.4 on 2026-06-12 10:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_starredfile_storedfile_starred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('require_email_verify', models.BooleanField(default=False)),
                ('allow_download', models.BooleanField(default=True)),
                ('download_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files_share_link',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShareLinkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_files', to='files.sharelink')),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_memberships', to='files.storedfile')),
            ],
            options={
                'db_table': 'files_share_link_file',
                'ordering': ('created_at',),
                'unique_together': {('share_link', 'stored_file')},
            },
        ),
        migrations.AddField(
            model_name='sharelink',
            name='files',
            field=models.ManyToManyField(related_name='share_links', through='files.ShareLinkFile', to='files.storedfile'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['created_by', 'is_active'], name='files_share_created_3b4287_idx'),
        ),
    ]
