# Generated by Django 5.1.4 on 2026-06-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_migrate_public_links_to_sharelinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='allowed_emails',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
