# Generated by Django 5.1.4 on 2026-06-15 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_sharelink_allowed_emails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trashed_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('pending_metadata', 'Pending metadata'), ('active', 'Active'), ('trashed', 'In trash'), ('deleted', 'Deleted')], db_index=True, default='uploading', max_length=20),
        ),
    ]
