# Generated by Django 5.1.4 on 2026-06-25 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_quota_bytes'),
        ('files', '0011_file_search_trigram_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='thumbnail_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(condition=models.Q(('status', 'active')), fields=['uploaded_at'], name='file_active_uploaded_at'),
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(condition=models.Q(('status', 'active')), fields=['expiry_date'], name='file_active_expiry_date'),
        ),
    ]
