# Generated by Django 5.1.4 on 2026-06-11 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('email_type', models.CharField(choices=[('assignment', 'File assignment'), ('welcome', 'Welcome'), ('expiry', 'Expiry reminder')], max_length=20)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('related_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications_log',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'email_type'], name='notificatio_status_10b386_idx')],
            },
        ),
    ]
